# Generated by Django 2.1.1 on 2018-09-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.CharField(max_length=10000000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
