# Generated by Django 2.1.1 on 2018-09-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AlterField(
            model_name='data',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
