# Generated by Django 2.1.1 on 2018-09-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180906_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='type',
            field=models.CharField(default='results', max_length=20),
            preserve_default=False,
        ),
    ]
